#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appdeploy
  labels:
    app: warehouse-app
spec:
  selector:
    matchLabels:
      app: warehouse-app
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: warehouse-app
    spec:
      containers:
      - name: appdeploy
        image: katikireddy1997/warehouse:0.0.1-SNAPSHOT
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000