#Service
apiVersion: v1
kind: Service
metadata:
  name: appdeploy
  labels:
    app: warehouse-app
spec:
  type: ClusterIP
  ports:
  - port: 8080
    protocol: TCP
    name: warehouse-app
  selector:
    app: warehouse-app